name: PowerFly
version: 0.1
description: A simple fly plugin
authors:
  - Santysx
api-version: 1.20
main: pwf.xenova.PowerFly
commands:
  fly:
    description: Fly for a limited time.
    usage: /fly
  powerfly:
    description: Main command for PowerFly plugin.
    usage: /powerfly <subcommand>
    subcommands:
      fly:
        description: Fly for a limited time.
        usage: /powerfly fly
      help:
        description: Help and info.
        usage: /powerfly help
      reload:
        description: Reloads the plugin configuration.
        usage: /powerfly reload
      check:
        description: Manage fly time.
        usage: /powerfly check <player>
      addflytime:
        description: Add fly time to a player.
        usage: /powerfly addflytime <player|all> <time>
      delflytime:
        description: Remove fly time from a player.
        usage: /powerfly delflytime <player|all> <time>
