name: PowerFly
version: 0.1
description: A simple fly plugin
authors:
  - Santysx
api-version: 1.20
main: pwf.xenova.PowerFly

commands:
  powerfly:
    description: Main command for PowerFly plugin.
    usage: Use /powerfly help to see the list of commands
    permission: powerfly.use
  fly:
    description: Enable or disable fly for a limited time.
    usage: /fly

permissions:
  powerfly.admin:
    description: Gives access to all admin commands of PowerFly.
    default: false
    children:
      powerfly.addflytime: true
      powerfly.delflytime: true
      powerfly.reload: true
      powerfly.check: true
  powerfly.addflytime:
    description: Allows using /powerfly addflytime
    default: op
  powerfly.delflytime:
    description: Allows using /powerfly delflytime
    default: op
  powerfly.reload:
    description: Allows using /powerfly reload
    default: op
  powerfly.check:
    description: Allows using /powerfly check
    default: op
  powerfly.help:
    description: Allows using /powerfly help
    default: op
  powerfly:
    description: Allows using /powerfly
    default: op
  powerfly.fly:
    description: Allows using /fly
    default: true

